apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clothes-api-igrs
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  rules:
    - host: clothes.local
      http:
        paths:
          - path: /graphql
            pathType: Prefix
            backend:
              service: 
                name: clothes-api-srv
                port: 
                  number: 8082
