apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/skaffold/api-dpl.yaml
      - ./infra/k8s/skaffold/api-srv.yaml
      - ./infra/k8s/skaffold/api-igrs.yaml
build:
  local:
    push: false
  artifacts:
    - image: rludena/clothes_api
      context: api
      docker:
        dockerfile: docker/dev.dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
